# Generated by Django 4.1.7 on 2023-03-30 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='posteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteo', to='ForoApp.post'),
        ),
    ]
