# Generated by Django 4.1.7 on 2023-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
