# Generated by Django 4.1.7 on 2023-03-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0004_profile_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
    ]
