# Generated by Django 4.1.7 on 2023-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0006_profile_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
    ]
